{% set name = "dash-daq" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_daq-{{ version }}.tar.gz
  sha256: 30c01bcd15d1c2d72b6097ca08c236ec3512a684f114717d0f88b24e55188014

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    # NOTE : The following are not present in the setup.py file.
    - dash >=1.0.0
    - dash-renderer
    - dash-html-components
    - dash-core-components

test:
  imports:
    - dash_daq

about:
  home: https://www.dashdaq.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Control components for Dash'
  doc_url: https://dash.plot.ly/dash-daq
  dev_url: https://github.com/plotly/dash-daq

extra:
  recipe-maintainers:
    - moorepants
