{% set name = "dash-daq" %}
{% set version = "0.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_daq-{{ version }}.tar.gz
  sha256: 8370e6624c2b2dd8c53ed8af9a5a376d4b4a8bb4eb4899b57ae8e55fdb8bad8f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dash >=1.6.0

test:
  imports:
    - dash_daq

about:
  home: https://www.dashdaq.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Control components for Dash'
  doc_url: https://dash.plot.ly/dash-daq
  dev_url: https://github.com/plotly/dash-daq

extra:
  recipe-maintainers:
    - moorepants
