{% set name = "dash-daq" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dash_daq-{{ version }}.tar.gz
  sha256: 051adb0ffc03e25f24bc031d40b858aa85bd3bae61450b150a24a5d13847d332

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - dash >=1.6.1

test:
  imports:
    - dash_daq

about:
  home: https://www.dashdaq.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Control components for Dash
  doc_url: https://dash.plot.ly/dash-daq
  dev_url: https://github.com/plotly/dash-daq

extra:
  recipe-maintainers:
    - moorepants
