travis:
  secure:
    BINSTAR_TOKEN: f4IbPPk0IrZAjBw2rQS46fHMTb5Qg7RwcSpnarSQgHyluyfSgWrrVq0gIz4WiUmUuKAIk2y2hgWbkXFUS1vSoJ4ovut6BMycJavIpaZeX7+18KkA9KCKsAfgBxs5jJBvaHCxTlF2kmA39Joh20jHuiOnrsp1Ua8lWFp7Hu4jOsBBJ96aa21nyILeH006zvFXtJsdXxkhg71AKBgFNov0+CKugkkScyNPvot1Dt7wq03bl+OXEPq5eTrQVm7kUVUfeLmCYNhL6pydzLcE9vWUi8e9KCQ96cCG+lwjr70WBYEIVen4CQ9jm3YDyoamiAhfME0TDV+pl+L4WfSqH/de9NG3gmpkZ/zkljGuWkk2Q0jH9gSn5aFjqHQ0ErbACiwVz/P9TqYOLnBbV2cfiwCd+EEhjk8baYgJu03/lLrXCmvPxPGS7YoSCzMdxLsxaYzAqIpVzYHkOfDny1KGP58dbZjKbRyGSIHShFjBaJ1Mm0H4jtl6usXBNVtlyNSESA34Ufk/ND26yed133hKXmYwL4TsXW5Nra/L+Ji431kX/9oBB0JTPsIyAOcumNRud53NOPl9JkaOZLquOF8gLuEVFYNtMdRLJMwKn7NvK0vApSzhjQPO++9DloJBgEa4sYgtrOhwvYCHbqB/zaD2/b2LWLow7rEuW08dWeoZ4wml/1U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
